version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eldrin-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eldrin
      POSTGRES_PASSWORD: eldrin_password
      POSTGRES_DB: eldrin_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eldrin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # You can add additional services here in the future:
  # - Redis for caching
  # - Minio for S3-compatible storage
  # - ElasticSearch for search capabilities
  # - RabbitMQ or Kafka for messaging

volumes:
  postgres_data: