/**
 * Generates worker/migrations.generated.ts from SQL files in migrations/
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const migrationsDir = join(rootDir, 'migrations');
const outputFile = join(rootDir, 'worker', 'migrations.generated.ts');

interface MigrationFile {
  name: string;
  content: string;
}

function generateMigrations(): void {
  let migrations: MigrationFile[] = [];

  if (existsSync(migrationsDir)) {
    const files = readdirSync(migrationsDir)
      .filter((f) => f.endsWith('.sql') && !f.endsWith('.rollback.sql'))
      .sort();

    migrations = files.map((filename) => ({
      name: filename,
      content: readFileSync(join(migrationsDir, filename), 'utf-8'),
    }));
  }

  const output = `// Auto-generated by scripts/generate-migrations.ts
// Do not edit manually

import type { MigrationFile } from '@eldrin-project/eldrin-app-core';

const migrations: MigrationFile[] = ${JSON.stringify(migrations, null, 2)};

export default migrations;
`;

  writeFileSync(outputFile, output, 'utf-8');
  console.log(`Generated ${outputFile} with ${migrations.length} migrations`);
}

generateMigrations();
