// Generated by Wrangler
interface Env {
  DB: D1Database;
  ASSETS: Fetcher;
  /** JWT secret shared with eldrin-core for token verification */
  JWT_SECRET: string;
  /** Factorial company API credentials */
  FACTORIAL_API_BASE_URL: string;
  FACTORIAL_API_KEY: string;
  /** Eldrin Core platform URL for event emission */
  ELDRIN_CORE_URL?: string;
}
